#!/usr/bin/env python2
#coding=utf-8
import os,sys

#### java path

JAVA_HOME=__import__('conf').JAVA_HOME
os.environ['PATH']=JAVA_HOME+'/bin'+':'+os.environ['PATH']

if len(sys.argv)<2:
    print 'presto shell客户端使用格式: presto-cli --server localhost:16060 --catalog hive --schema default'
    os.system('java -version && '+sys.path[0]+'/presto-cli-*-executable.jar '+'--server localhost:16060 --catalog hive --schema default')
else:
#print 'java -version && '+sys.path[0]+'/presto-cli-*-executable.jar '+ ' '.join(str(i) for i in sys.argv[1:])
    os.system('java -version && '+sys.path[0]+'/presto-cli-*-executable.jar '+ ' '.join(str(i) for i in sys.argv[1:]))

